name: "Podcasst1 Generator"
author: "Anil"
description: "Generates a feed for podcast from a YAML file"
runs:
  using: "docker"
  image: "Docerfile"
branding:
   icon: "git-branch"
   color: "red"
inputs:
  email:
   description: The Commiter's email address
   required: true
   default: ${{ github.actor }}@localhost
name:
  description: The committer's name
  required: true
  default: #{{ github.actor }}